# Example configuration file for notes-tui
# Copy this to ~/.config/notes-tui/config.toml and customize

# Default directory for notes
# If not set, uses current directory or ~/notes if it exists
notes_directory = "/Users/mph/notes"

# Editor command with arguments
# Supports commands with spaces and arguments
# If not set, falls back to $EDITOR environment variable
editor = "emacsclient --create-frame --no-wait"

# External preview command (optional)
# Use tools like glow, bat, or any markdown viewer
# If not set, Enter key uses internal preview
# If set, Enter key uses this external command instead
preview_command = "glow --style dark --pager"

# Add YAML frontmatter to new notes (optional)
# If true, new notes get frontmatter with title and date
# If false or not set, new notes use simple markdown headers
add_frontmatter = false

# Enable Denote-style filenames for new notes (optional)
# If true, new notes are created with format: YYYYMMDDTHHMMSS-title.md
# Example: 20250623T093045-meeting-notes.md
# When used with add_frontmatter=true, adds "identifier" field to frontmatter
denote_filenames = false

# Show extracted titles instead of filenames in list (optional)
# If true, displays note titles from frontmatter or first heading
# If false, shows filenames as before
show_titles = false

# Other example configurations:
# editor = "code --wait"              # VS Code
# editor = "vim"                      # Simple vim
# preview_command = "bat --style=plain --color=always"  # bat with color
# preview_command = "mdcat"           # mdcat viewer
