# Test configuration for Denote features
notes_directory = "/Users/mph/code/notes-tui/test-notes"
editor = "vim"
add_frontmatter = true
denote_filenames = true
show_titles = true
taskwarrior_support = false  # Disabled for testing without TaskWarrior
theme = "light"  # Test light theme
